In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import pickle
import os
import matplotlib.pyplot as plt

# commands if you run the model on GPU
physicaldevices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physicaldevices[0],True)

In [2]:
pickle_in = open("X_Numbers.pickle",'rb')
X = pickle.load(pickle_in)
pickle_in = open("Y_Numbers.pickle",'rb')
Y = pickle.load(pickle_in)
print(Y.shape)
print(X.shape)

(15000, 1)
(15000, 64, 64, 3)


In [3]:
X_train = X/255
Y_train = Y

In [4]:
X_valid = X[10000:13000,:]/255
Y_valid = Y[10000:13000,:]

print(X_valid.shape)

(3000, 64, 64, 3)


In [5]:
X_test = X[13000:15000,:]/255
Y_test = Y[13000:15000,:]

In [6]:
print(X_train.shape)
print(Y_train.shape)

(15000, 64, 64, 3)
(15000, 1)


In [7]:
# sequential API 

model = keras.Sequential(
    [
        keras.Input(shape=(64,64,3)),
        layers.Conv2D(64,(3,3),padding='same',activation='relu'),
        layers.MaxPooling2D(),
        layers.Conv2D(64,(3,3),padding='same',activation='relu'),
        layers.MaxPooling2D(),
        layers.Flatten(),
        layers.Dense(512,activation="relu"),
        layers.Dense(256,activation="relu"),
        layers.Dense(10),
    ]
)

model.compile(
#     sparse if you don't have output in one hot encoding
#     without sparse if you have output in one hot encoding
    loss = keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer = keras.optimizers.Adam(learning_rate=0.0001),
    metrics = ['accuracy']
)

In [8]:
model.fit(X_train,Y_train,batch_size=64,epochs=50,verbose=2)


Epoch 1/50
235/235 - 67s - loss: 1.8349 - accuracy: 0.3834 - 67s/epoch - 285ms/step
Epoch 2/50
235/235 - 57s - loss: 1.0106 - accuracy: 0.6950 - 57s/epoch - 242ms/step
Epoch 3/50
235/235 - 57s - loss: 0.7035 - accuracy: 0.7930 - 57s/epoch - 241ms/step
Epoch 4/50
235/235 - 57s - loss: 0.5087 - accuracy: 0.8504 - 57s/epoch - 241ms/step
Epoch 5/50
235/235 - 57s - loss: 0.3708 - accuracy: 0.8897 - 57s/epoch - 241ms/step
Epoch 6/50
235/235 - 57s - loss: 0.2775 - accuracy: 0.9172 - 57s/epoch - 242ms/step
Epoch 7/50
235/235 - 57s - loss: 0.2043 - accuracy: 0.9423 - 57s/epoch - 242ms/step
Epoch 8/50
235/235 - 57s - loss: 0.1516 - accuracy: 0.9581 - 57s/epoch - 242ms/step
Epoch 9/50
235/235 - 57s - loss: 0.1148 - accuracy: 0.9703 - 57s/epoch - 241ms/step
Epoch 10/50
235/235 - 57s - loss: 0.0867 - accuracy: 0.9791 - 57s/epoch - 241ms/step
Epoch 11/50
235/235 - 57s - loss: 0.0609 - accuracy: 0.9871 - 57s/epoch - 241ms/step
Epoch 12/50
235/235 - 57s - loss: 0.0451 - accuracy: 0.9918 - 57s/epoch - 

In [9]:
model.evaluate(X_valid,Y_valid,batch_size=32,verbose=2)

94/94 - 1s - loss: 8.5718e-05 - accuracy: 1.0000 - 610ms/epoch - 6ms/step


[8.571816579205915e-05, 1.0]

In [10]:
model.evaluate(X_test,Y_test,batch_size=32,verbose=2)

63/63 - 0s - loss: 9.3669e-05 - accuracy: 1.0000 - 329ms/epoch - 5ms/step


[9.366931772092357e-05, 1.0]

In [11]:
outputs=model.predict(X_test)

In [12]:
print(outputs[1])

[ -2.0228746 -14.431135   -9.702845   -2.6083663  -1.5856878   2.5023043
   1.1427256   4.4675207  -1.2471173  30.34489  ]


In [13]:
print(Y_test[1])

[9]


In [14]:
index = tf.argmax(outputs, axis=1)

In [15]:
print(index)

tf.Tensor([5 9 6 ... 0 2 1], shape=(2000,), dtype=int64)


In [16]:
print(Y_test)

[[5]
 [9]
 [6]
 ...
 [0]
 [2]
 [1]]


In [23]:
op2 = model.predict(X_test[10].reshape(1,64,64,3))

In [24]:
print(op2)

[[ 22.247545  -11.10685    -5.874484   -7.109452    0.759037   -7.628192
    1.4291774  10.899167   -3.0577717 -13.772945 ]]


In [25]:
i = tf.argmax(op2,axis=1)

In [26]:
print(i)

tf.Tensor([0], shape=(1,), dtype=int64)
